### ISSUE TITLE
Plugin doesn't work in Pycharm??

### ISSUE THREAD

**Issue by subhashsharma** [kivymd/JetBrainsMDKVCompletion#1]
### Description of the Bug

I tried loading the zip file to plugins area of Pycharm and see below, I get an error:

### Screenshots

![image](https://github.com/kivymd/JetBrainsMDKVCompletion/assets/4167913/14f389ce-d1fd-4b80-9a0a-d3b8e5afbceb)

### Versions
Pycharm 2023.2 (Community Edition)
* Build #PC-232.8660.197, built on July 26, 2023
* Runtime version: 17.0.7+7-b1000.6 aarch64
* VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Mordechay0000** [comment]
I am also facing the same problem.
Did you find a solution?

**Comment by HeaTTheatR** [comment]
https://github.com/noembryo/KV4Jetbrains
